# packages
IF (SIMPLE_GL_ANDROID)
ELSE (SIMPLE_GL_ANDROID)
	FIND_PACKAGE (OpenGL    REQUIRED)
	FIND_PACKAGE (SDL)
	FIND_PACKAGE (SDL_image)
	FIND_PACKAGE (DevIL)

	SET(GLEW_USE_STATIC_LIB OFF)
	FIND_PACKAGE (Glew      REQUIRED)

	# Qt. Module sends FATAL_ERROR, so need to check before use
	IF (BUILD_QT_EXAMPLES)
		FIND_PACKAGE (Qt4)
	ENDIF (BUILD_QT_EXAMPLES)
ENDIF (SIMPLE_GL_ANDROID)

# Documentation
FIND_PACKAGE (Doxygen)